### ISSUE TITLE
Возможность остановить загрузку песни.

### ISSUE THREAD

**Issue by Flexlug** [fataliti/Fatalny-Direct#1]
У меня никак не получается остановить загрузку битмапы при мисклике.

Возможно просто эта опция расположения в не самом очевидном месте о_0. По крайней мере в обычном osu!direct можно остановить загрузку просто кликнув по песне в очереди загрузки.

**Comment by fataliti** [comment]
Чисто технически такой возможности не было, однако теперь такая возможность появилась начиная с версии 1.3.0
