### ISSUE TITLE
ERROR in action number 1 of Async Event: HTTP

### ISSUE THREAD

**Issue by AutumnVN** [fataliti/Fatalny-Direct#4]
___________________________________________
############################################################################################
ERROR in
action number 1
of Async Event: HTTP
for object o_control:

JSON parse error############################################################################################
gml_Object_o_control_Other_62 (line 14)

___________________________________________
############################################################################################
ERROR in
action number 1
of Async Event: HTTP
for object o_control:

JSON parse error############################################################################################
gml_Object_o_control_Other_62 (line 14)

___________________________________________
############################################################################################
ERROR in
action number 1
of Async Event: HTTP
for object o_tillerinobot:

JSON parse error############################################################################################
gml_Object_o_tillerinobot_Other_62 (line 7)

**Comment by fataliti** [comment]
уъуъуъуъу

**Comment by AutumnVN** [comment]
> уъуъуъуъу

What does this mean? I don't know.
